name: Publish Docker

on:
  push:
    branches: [ main ]
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: oostvoort/siwe_oidc
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        tag_semver: true
        snapshot: true
